### PR TITLE
Add extra deps to Docker build

### PR DESCRIPTION
**Pull request by adammcmaster**
And add docker-compose.yml

### CODE REVIEW

**Comment by adammcmaster** [comment]
This adds a default set of sci/data packages, which I would imagine a lot of people would want to use.

**Comment by adammcmaster** [comment]
Oh, this will also close #1

**Review by camallen — APPROVED** [review]
LGTM - should the `start_notebooks.sh` script be updated to use docker compose or is that just another dep that a user doesn't need?

**Comment by adammcmaster** [comment]
I think it's good to keep the script too if people don't want to install compose.

**Pull request merged**
